frameworks:
  ColorVideoVDP:
    gpu_mem: 16
    metric: cvvdp
    workdir: methods/ColorVideoVDP

  HDRMetrics:
    hdrtools_bin: methods/HDRTools/build/bin
    wpsnr_cfg: methods/HDRTools/cfg/HDRMetricsYUV.cfg
    hdrconvert_cfg: methods/HDRTools/cfg/JCTVC_CTC_cfgFiles/YCbCr/HDRConvertYCbCr420ToEXR2020.cfg
    deltae_cfg: methods/HDRTools/cfg/JCTVC_CTC_cfgFiles/YCbCr/HDRMetric_CfE.cfg
    weight_table: methods/HDRTools/cfg/hdrTable.txt
    width: 3840
    height: 2160
    bit_depth: 10
    workdir: methods/HDRMetrics

  VMAF:
    b: 10
    h: 2160
    vmaf_bin: methods/vmaf/libvmaf/build/tools/vmaf
    model: path=methods/vmaf/model/vmaf_4k_v0.6.1.json
    p: '420'
    w: 3840
    enable_pu21: false

global:
  device: cuda:0
  num_workers: 4
  output_dir: /mnt/bn/public-vqa1/wangjiayi/hdr-vqa-outputs/zjuhdr_lab_cvvdp_display_models

datasets:
    ZJUHDR_HW:
        type: TestVideoSet
        test_data: /mnt/bn/public-vqa1/wangjiayi/playground/hdr-vqa/ZJUHDR-info-mp4-HW.csv
        ref_dir: /mnt/bn/public-vqa1/wangjiayi/ZJUHDR/ref_mp4
        dis_dir: /mnt/bn/public-vqa1/wangjiayi/ZJUHDR/val_mp4
        display_model_by_trc:
          PQ: avs_hdr_set2_pq
          HLG: avs_hdr_set2_hlg
        lower_better: False

    ZJUHDR_MLS:
        type: TestVideoSet
        test_data: /mnt/bn/public-vqa1/wangjiayi/playground/hdr-vqa/ZJUHDR-info-mp4-MLS.csv
        ref_dir: /mnt/bn/public-vqa1/wangjiayi/ZJUHDR/ref_mp4
        dis_dir: /mnt/bn/public-vqa1/wangjiayi/ZJUHDR/val_mp4
        display_model_by_trc:
          PQ: avs_hdr_set3_pq
          HLG: avs_hdr_set3_hlg
        lower_better: False

    ZJUHDR_WHU:
        type: TestVideoSet
        test_data: /mnt/bn/public-vqa1/wangjiayi/playground/hdr-vqa/ZJUHDR-info-mp4-WHU.csv
        ref_dir: /mnt/bn/public-vqa1/wangjiayi/ZJUHDR/ref_mp4
        dis_dir: /mnt/bn/public-vqa1/wangjiayi/ZJUHDR/val_mp4
        display_model_by_trc:
          PQ: avs_hdr_set2_pq
          HLG: avs_hdr_set2_hlg
        lower_better: False
runs:
- datasets:
  - ZJUHDR_HW
  - ZJUHDR_MLS
  - ZJUHDR_WHU
  framework: ColorVideoVDP




